name: Build On PR

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: "Build the project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: "Install Dependencies"
        uses: npm install
      - name: "Build"
        uses: npm run build
