name: "Deploy on EC2"
on:
  push:
    branches:
      - main
jobs:
  build-docker-and-push:
    name: "Builds docker and updates EC2"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v2
      - name: "Login to Docker"
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: "Build and Push to Docker Hub"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: amannabidev/deployment-app:latest
      - name: "Verify the Docker Image"
        run: docker pull amannabidev/deployment-app:latest
  deploy-to-ec2:
    name: "Deploy to EC2"
    runs-on: ubuntu-latest
    needs: build-docker-and-push
    steps:
      - name: "SSH into Machine"
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.MACHINE_HOST}}
          username: ${{secrets.MACHINE_USERNAME}}
          key: ${{secrets.MACHINE_SSH_KEY}}
          script: |
            docker pull amannabidev/deployment-app:latest
            docker stop web-app || true
            docker rm web-app || true
            docker run -d --name web-app -p 3000:3000 amannabidev/deployment-app:latest
