name: "Lint project"
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: "Lint"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Clone"
        uses: actions/checkout@v3
      - name: Use Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: "Install Dependencies"
        run: npm install
      - name: "Build"
        run: npm run lint

